export const REGISTER_MEMBER = `${import.meta.env.VITE_API_BASE_URL}api/members/createMember`;
export const GET_MEMBER_BY_ID = `${import.meta.env.VITE_API_BASE_URL}api/members/getmemberbyid`;
export const GET_ALL_MEMBERS= `${import.meta.env.VITE_API_BASE_URL}api/members/getallmembers`;
export const UPDATE_MEMBER_DETAILS= `${import.meta.env.VITE_API_BASE_URL}api/members/updatemember`;
export const LOGIN=`${import.meta.env.VITE_API_BASE_URL}api/user/userlogin`;
export const ALL_SYSTEM_USERS=`${import.meta.env.VITE_API_BASE_URL}api/User/allusers`
export const ALL_SYSTEM_ROLES=`${import.meta.env.VITE_API_BASE_URL}api/Roles/GetActiveRoles`
export const REGISTER_SYSTEM_USER=`${import.meta.env.VITE_API_BASE_URL}api/User/UserRegistration`
export const REGISTER_ACCOUNT_CLASS=`${import.meta.env.VITE_API_BASE_URL}api/Accounts/addaccountclass`
export const GET_ACCOUNT_CLASS=`${import.meta.env.VITE_API_BASE_URL}api/Accounts/listaccountclasses`